# Email Spam Detection with Machine Learning

# Import Library

In [1]:
#Import Basic Library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
import seaborn as sns
%matplotlib inline

In [2]:
#Read the Dataset
df=pd.read_csv('spam.csv',encoding='latin-1')

In [3]:
print(df)

        v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  


# Data Preprocessing

In [4]:
#Drop Last 3 columns
df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)

In [5]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
print(df)

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]


In [7]:
#Renaming the columns
df.rename(columns={'v1':'Category','v2':'Message'},inplace=True)

In [8]:
print(df)

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham              Will Ì_ b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]


In [9]:
#replace null value with null string
df1=df.where((pd.notnull(df)),'')

In [10]:
df1.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [11]:
df1.shape

(5572, 2)

# Label Encoding

In [12]:
df1.loc[df1['Category'] == 'spam','Category']= 0 
df1.loc[df1['Category'] == 'ham','Category']= 1

In [13]:
#Split Independent and Dependent Columns
x=df1['Message']
y=df1['Category']
print(x)
print(y)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object
0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object


In [14]:
#Split the data into train and test data

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [15]:
print(x.shape)
print(x_train.shape)
print(x_test.shape)

(5572,)
(4457,)
(1115,)


# Feature Extraction

In [16]:
feature_extraction= TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)

In [17]:
x_train_features=feature_extraction.fit_transform(x_train)
x_test_features=feature_extraction.transform(x_test)

In [18]:
y_train=y_train.astype('int')
y_test=y_test.astype('int')

In [19]:
print(x_train)

3890    No problem. We will be spending a lot of quali...
5553                          Hahaha..use your brain dear
4366    I like dis sweater fr mango but no more my siz...
3968    Thanks for your message. I really appreciate y...
3771                Does uncle timi help in clearing cars
                              ...                        
3335                         Then u go back urself lor...
1099    Been up to ne thing interesting. Did you have ...
2514        Ok ill send you with in  &lt;DECIMAL&gt;  ok.
3606                         I have no idea where you are
2575                 Now thats going to ruin your thesis!
Name: Message, Length: 4457, dtype: object


In [20]:
print(x_train_features)

  (0, 6566)	0.29071829686789585
  (0, 5260)	0.5087678982336444
  (0, 4010)	0.4050685955975014
  (0, 6073)	0.5665799184805557
  (0, 5169)	0.4141795823412651
  (1, 2116)	0.3523355719340784
  (1, 1423)	0.5940444343697558
  (1, 6859)	0.4124100686677272
  (1, 3141)	0.5940444343697558
  (2, 3565)	0.40508027557608417
  (2, 5897)	0.440107047813195
  (2, 4140)	0.440107047813195
  (2, 2845)	0.3382880530026162
  (2, 6332)	0.440107047813195
  (2, 2258)	0.3104925886287087
  (2, 3910)	0.20972094634778068
  (3, 2105)	0.17893490557083572
  (3, 7191)	0.2812743655569581
  (3, 1763)	0.2431679156261037
  (3, 6620)	0.2114722422733664
  (3, 6461)	0.2757210982911898
  (3, 7045)	0.20776132213481782
  (3, 4865)	0.26062868324883703
  (3, 2251)	0.2952674814882996
  (3, 5175)	0.3101007821209402
  :	:
  (4451, 4355)	0.5653315538937795
  (4452, 6856)	0.8442476281269602
  (4452, 4003)	0.5359533024452802
  (4453, 7234)	0.3927126429320925
  (4453, 4634)	0.3513960490954625
  (4453, 4498)	0.36145784624804855
  (4453, 35

In [21]:
print(x_test_features)

  (0, 6514)	0.32916662990172807
  (0, 4698)	0.4620063190302294
  (0, 2485)	0.3557824864541254
  (0, 2300)	0.36426616984882515
  (0, 2105)	0.25507748700491606
  (0, 1627)	0.4752353063146944
  (0, 1153)	0.35779232807132594
  (1, 6514)	0.2538071933796766
  (1, 5461)	0.3795854222400133
  (1, 5420)	0.28452995524622654
  (1, 5169)	0.27748341675755483
  (1, 4974)	0.36643489446871863
  (1, 3994)	0.3562345526694059
  (1, 2856)	0.19166908649350406
  (1, 2219)	0.2241098298890172
  (1, 1010)	0.3981200501333143
  (1, 446)	0.3562345526694059
  (2, 7045)	0.545123558876406
  (2, 4665)	0.6548438540730855
  (2, 2069)	0.5234690366589309
  (3, 6483)	0.41989427581549055
  (3, 4637)	0.5752520807193355
  (3, 3113)	0.44855177661259954
  (3, 1717)	0.5399769851235704
  (4, 7209)	0.19560995892120994
  :	:
  (1109, 2002)	0.28348303017817333
  (1109, 1865)	0.29637123808289095
  (1109, 1468)	0.3153928537769968
  (1109, 1397)	0.27996157444650627
  (1109, 390)	0.3153928537769968
  (1110, 4086)	0.4470646150528683
  (1

# Training the Model

In [22]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
model= LogisticRegression()

In [23]:
model.fit(x_train_features,y_train)

LogisticRegression()

In [24]:
#Prediction on Training data
train_y_pred=model.predict(x_train_features)

In [25]:
train_y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [26]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_train,train_y_pred)
print(accuracy)

0.971729863136639


In [27]:
test_y_pred=model.predict(x_test_features)
test_y_pred

array([1, 1, 1, ..., 1, 1, 1])

# Evaluating the Model

In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,test_y_pred))
print(classification_report(y_test,test_y_pred))
accuracy=accuracy_score(y_test,test_y_pred)
print(accuracy)

[[109  49]
 [  0 957]]
              precision    recall  f1-score   support

           0       1.00      0.69      0.82       158
           1       0.95      1.00      0.98       957

    accuracy                           0.96      1115
   macro avg       0.98      0.84      0.90      1115
weighted avg       0.96      0.96      0.95      1115

0.9560538116591928


In [29]:
print("Accuracy of the model:",accuracy)

Accuracy of the model: 0.9560538116591928
